### ISSUE TITLE
Overflow panic in sw-composite

### ISSUE THREAD

**Issue by FloVanGH** [jrmuizel/raqote#162]
Someone is trying to create a [plotters](https://github.com/38/plotters) OrbTk backend. On debug there is a overflow panic on sw-composite. On release it doesn't panic but does not draw everything. Complete description of the issue: https://github.com/redox-os/orbtk/issues/343.

Any ideas? I will check it in detail.

**Comment by FloVanGH** [comment]
The origin of the  bug is in OrbTk.

**Comment by jrmuizel** [comment]
What was it?

**Comment by FloVanGH** [comment]
> Disregard my last post, I think I found the problem. The application only panics when using rgba and it seems like using rgb and set_alpha on the RenderContext2D works. I guess the alpha is used twice then using rgba colors and that's what causes the overflow.

**Comment by arctic-alpaca** [comment]
What is the reason for using rgba in `SolidSource` and  then also using alpha in `DrawOptions`? Or maybe the better question, how is it intended to be used? I think this is what might have caused the panic, since switching to rgb and using the `DrawOptions` alpha didn't panic. But I'm not entirely sure that's the whole story.

**Comment by FloVanGH** [comment]
It is an historical reason. First I've started with rgba and from styling perspective I decided to switch to an opacity setting. I have to check the whole implementation and to switch to one of this two options only.
